FROM node:20

WORKDIR /frontend

COPY package*.json ./
RUN npm install --save-dev vite @vitejs/plugin-react 
RUN npm install 

COPY . .

RUN npm run build -- --mode production

FROM nginx:alpine

COPY --from=0 /frontend/dist /usr/share/nginx/html

CMD ["nginx", "-g", "daemon off;"]
